using Microsoft.AspNetCore.Mvc;

namespace FlightFocus.Controllers
{
    [ApiController]
    public class GetAirportRequest : ControllerBase
    {
        [HttpGet("api/boarding/airport")]
        public IActionResult GetAirport()
        {
            var list = new List<object>();

            list.Add(new { name = "ALG", fullName = "Houari Boumediene Airport", longitude = 3.2156, latitude = 36.6914 });
            list.Add(new { name = "LAD", fullName = "Quatro de Fevereiro Airport", longitude = 13.2314, latitude = -8.8583 });
            list.Add(new { name = "COO", fullName = "Cardinal Bernardin Gantin International Airport", longitude = 2.4214, latitude = 6.3583 });
            list.Add(new { name = "GBE", fullName = "Sir Seretse Khama International Airport", longitude = 25.9183, latitude = -24.5556 });
            list.Add(new { name = "OUA", fullName = "Ouagadougou International Airport", longitude = -1.5147, latitude = 12.3536 });
            list.Add(new { name = "BJM", fullName = "Bujumbura International Airport", longitude = 29.3583, latitude = -3.3742 });
            list.Add(new { name = "DLA", fullName = "Douala International Airport", longitude = 9.7197, latitude = 4.0056 });
            list.Add(new { name = "NSI", fullName = "Yaoundé Nsimalen International Airport", longitude = 11.5183, latitude = 3.8483 });
            list.Add(new { name = "N'DJ", fullName = "N'Djamena International Airport", longitude = 15.0447, latitude = 12.1342 });
            list.Add(new { name = "HAH", fullName = "Prince Said Ibrahim International Airport", longitude = 43.2556, latitude = -11.5936 });
            list.Add(new { name = "ABJ", fullName = "Félix-Houphouët-Boigny International Airport", longitude = -3.9319, latitude = 5.2614 });
            list.Add(new { name = "FIH", fullName = "N'djili International Airport", longitude = 15.4442, latitude = -4.3861 });
            list.Add(new { name = "DJJ", fullName = "Djibouti–Ambouli International Airport", longitude = 43.1597, latitude = 11.5958 });
            list.Add(new { name = "CAI", fullName = "Cairo International Airport", longitude = 31.2357, latitude = 30.1219 });
            list.Add(new { name = "SSG", fullName = "Malabo International Airport", longitude = 8.7481, latitude = 3.7556 });
            list.Add(new { name = "ASM", fullName = "Asmara International Airport", longitude = 38.9106, latitude = 15.2917 });
            list.Add(new { name = "ADD", fullName = "Addis Ababa Bole International Airport", longitude = 38.7997, latitude = 9.0056 });
            list.Add(new { name = "LBV", fullName = "Libreville International Airport", longitude = 9.4531, latitude = 0.4167 });
            list.Add(new { name = "ACC", fullName = "Kotoka International Airport", longitude = -0.2056, latitude = 5.6056 });
            list.Add(new { name = "CKY", fullName = "Conakry International Airport", longitude = -13.5783, latitude = 9.5833 });
            list.Add(new { name = "OXB", fullName = "Osvaldo Vieira International Airport", longitude = -15.9806, latitude = 11.8697 });
            list.Add(new { name = "NBO", fullName = "Jomo Kenyatta International Airport", longitude = 36.9275, latitude = -1.3192 });
            list.Add(new { name = "SHO", fullName = "Matsapha Airport", longitude = 31.3667, latitude = -26.5167 });
            list.Add(new { name = "MSU", fullName = "Maseru International Airport", longitude = 27.5000, latitude = -29.3833 });
            list.Add(new { name = "ROB", fullName = "Roberts International Airport", longitude = -9.4292, latitude = 6.2364 });
            list.Add(new { name = "TIP", fullName = "Tripoli International Airport", longitude = 13.1606, latitude = 32.6639 });
            list.Add(new { name = "TNR", fullName = "Ivato International Airport", longitude = 47.4783, latitude = -18.7992 });
            list.Add(new { name = "LLW", fullName = "Kamuzu International Airport", longitude = 33.7786, latitude = -13.7892 });
            list.Add(new { name = "BKO", fullName = "Modibo Keita International Airport", longitude = -7.9547, latitude = 12.6392 });
            list.Add(new { name = "NKC", fullName = "Nouakchott–Oumtounsy International Airport", longitude = -15.9672, latitude = 18.0806 });
            list.Add(new { name = "MRU", fullName = "Lungi International Airport", longitude = -13.2114, latitude = 8.6172 });
            list.Add(new { name = "CMN", fullName = "Mohammed V International Airport", longitude = -7.5892, latitude = 33.3678 });
            list.Add(new { name = "MPM", fullName = "Maputo International Airport", longitude = 32.5725, latitude = -25.9206 });
            list.Add(new { name = "WDH", fullName = "Hosea Kutako International Airport", longitude = 15.4436, latitude = -22.4828 });
            list.Add(new { name = "NIM", fullName = "Diori Hamani International Airport", longitude = 13.4814, latitude = 13.4833 });
            list.Add(new { name = "LOS", fullName = "Murtala Muhammed International Airport", longitude = 3.3214, latitude = 6.5778 });
            list.Add(new { name = "RAI", fullName = "Nelson Mandela International Airport", longitude = -23.5083, latitude = 15.0153 });
            list.Add(new { name = "COO", fullName = "Maya-Maya Airport", longitude = 15.3136, latitude = -4.2667 });
            list.Add(new { name = "KGL", fullName = "Kigali International Airport", longitude = 30.1397, latitude = -1.9667 });
            list.Add(new { name = "HLE", fullName = "Saint Helena Airport", longitude = -5.7014, latitude = -15.9658 });
            list.Add(new { name = "DSS", fullName = "Blaise Diagne International Airport", longitude = -15.0133, latitude = 14.7392 });
            list.Add(new { name = "SEZ", fullName = "Seychelles International Airport", longitude = 55.5214, latitude = -4.6742 });
            list.Add(new { name = "FNA", fullName = "Lungi International Airport", longitude = -13.2114, latitude = 8.6172 });
            list.Add(new { name = "MGQ", fullName = "Aden Adde International Airport", longitude = 45.0156, latitude = 2.0203 });
            list.Add(new { name = "CPT", fullName = "Cape Town International Airport", longitude = 18.6016, latitude = -33.9648 });
            list.Add(new { name = "JUB", fullName = "Juba International Airport", longitude = 31.6014, latitude = 4.8728 });
            list.Add(new { name = "KRT", fullName = "Khartoum International Airport", longitude = 32.5536, latitude = 15.5892 });
            list.Add(new { name = "TMS", fullName = "São Tomé International Airport", longitude = 6.7136, latitude = 0.3653 });
            list.Add(new { name = "DAR", fullName = "Julius Nyerere International Airport", longitude = 39.2028, latitude = -6.8783 });
            list.Add(new { name = "BJL", fullName = "Banjul International Airport", longitude = -16.6528, latitude = 13.2892 });
            list.Add(new { name = "LFW", fullName = "Lomé–Tokoin International Airport", longitude = 1.2536, latitude = 6.1375 });
            list.Add(new { name = "TUN", fullName = "Tunis–Carthage International Airport", longitude = 10.2278, latitude = 36.8514 });
            list.Add(new { name = "EBB", fullName = "Entebbe International Airport", longitude = 32.4436, latitude = 0.0428 });
            list.Add(new { name = "RBA", fullName = "Rabat–Salé Airport", longitude = -6.8042, latitude = 34.0208 });
            list.Add(new { name = "LUN", fullName = "Kenneth Kaunda International Airport", longitude = 28.4522, latitude = -15.3319 });
            list.Add(new { name = "HRE", fullName = "Robert Gabriel Mugabe International Airport", longitude = 31.0928, latitude = -17.9319 });
            list.Add(new { name = "KBL", fullName = "Kabul International Airport", longitude = 69.2106, latitude = 34.5656 });
            list.Add(new { name = "EVN", fullName = "Zvartnots International Airport", longitude = 44.3958, latitude = 40.1472 });
            list.Add(new { name = "GYD", fullName = "Heydar Aliyev International Airport", longitude = 50.0467, latitude = 40.4675 });
            list.Add(new { name = "BAH", fullName = "Bahrain International Airport", longitude = 50.6339, latitude = 26.2708 });
            list.Add(new { name = "DAC", fullName = "Hazrat Shahjalal International Airport", longitude = 90.4006, latitude = 23.8428 });
            list.Add(new { name = "PBH", fullName = "Paro International Airport", longitude = 89.4236, latitude = 27.4242 });
            list.Add(new { name = "BWN", fullName = "Brunei International Airport", longitude = 114.9283, latitude = 4.9442 });
            list.Add(new { name = "PNH", fullName = "Phnom Penh International Airport", longitude = 104.8397, latitude = 11.5617 });
            list.Add(new { name = "PEK", fullName = "Beijing Capital International Airport", longitude = 116.5846, latitude = 40.0801 });
            list.Add(new { name = "LCA", fullName = "Larnaca International Airport", longitude = 33.6250, latitude = 34.8750 });
            list.Add(new { name = "FNJ", fullName = "Pyongyang International Airport", longitude = 125.6667, latitude = 39.2 });
            list.Add(new { name = "TBS", fullName = "Tbilisi International Airport", longitude = 44.9631, latitude = 41.6778 });
            list.Add(new { name = "HKG", fullName = "Hong Kong International Airport", longitude = 113.915, latitude = 22.3089 });
            list.Add(new { name = "DEL", fullName = "Indira Gandhi International Airport", longitude = 77.0999, latitude = 28.5562 });
            list.Add(new { name = "CGK", fullName = "Soekarno-Hatta International Airport", longitude = 106.6559, latitude = -6.1256 });
            list.Add(new { name = "IKA", fullName = "Tehran Imam Khomeini International Airport", longitude = 51.1525, latitude = 35.2136 });
            list.Add(new { name = "BGW", fullName = "Baghdad International Airport", longitude = 44.2322, latitude = 33.2639 });
            list.Add(new { name = "TLV", fullName = "Ben Gurion International Airport", longitude = 34.8700, latitude = 32.0114 });
            list.Add(new { name = "HND", fullName = "Tokyo Haneda Airport", longitude = 139.7798, latitude = 35.5494 });
            list.Add(new { name = "AMM", fullName = "Queen Alia International Airport", longitude = 35.9933, latitude = 31.7222 });
            list.Add(new { name = "ALA", fullName = "Almaty International Airport", longitude = 77.0403, latitude = 43.3525 });
            list.Add(new { name = "KWI", fullName = "Kuwait International Airport", longitude = 47.9783, latitude = 29.2261 });
            list.Add(new { name = "FRU", fullName = "Manas International Airport", longitude = 74.4897, latitude = 43.0708 });
            list.Add(new { name = "VTE", fullName = "Wattay International Airport", longitude = 102.5975, latitude = 17.9758 });
            list.Add(new { name = "BEY", fullName = "Beirut Rafic Hariri International Airport", longitude = 35.4931, latitude = 33.8206 });
            list.Add(new { name = "MFM", fullName = "Macau International Airport", longitude = 113.5917, latitude = 22.1494 });
            list.Add(new { name = "KUL", fullName = "Kuala Lumpur International Airport", longitude = 101.7093, latitude = 2.7456 });
            list.Add(new { name = "MLE", fullName = "Velana International Airport", longitude = 73.5292, latitude = 4.1914 });
            list.Add(new { name = "ULN", fullName = "Chinggis Khaan International Airport", longitude = 106.7925, latitude = 47.8431 });
            list.Add(new { name = "RGN", fullName = "Yangon International Airport", longitude = 96.1364, latitude = 16.9072 });
            list.Add(new { name = "KTM", fullName = "Tribhuvan International Airport", longitude = 85.3569, latitude = 27.6969 });
            list.Add(new { name = "MCT", fullName = "Muscat International Airport", longitude = 58.2847, latitude = 23.5936 });
            list.Add(new { name = "KHI", fullName = "Jinnah International Airport", longitude = 67.1606, latitude = 24.8914 });
            list.Add(new { name = "MNL", fullName = "Ninoy Aquino International Airport", longitude = 121.0194, latitude = 14.5144 });
            list.Add(new { name = "DOH", fullName = "Hamad International Airport", longitude = 51.6131, latitude = 25.2764 });
            list.Add(new { name = "ICN", fullName = "Incheon International Airport", longitude = 126.4500, latitude = 37.4600 });
            list.Add(new { name = "JED", fullName = "King Abdulaziz International Airport", longitude = 39.1561, latitude = 21.6706 });
            list.Add(new { name = "SIN", fullName = "Singapore Changi Airport", longitude = 103.9915, latitude = 1.3502 });
            list.Add(new { name = "CMB", fullName = "Bandaranaike International Airport", longitude = 79.8844, latitude = 7.1806 });
            list.Add(new { name = "DAM", fullName = "Damascus International Airport", longitude = 36.5150, latitude = 33.4114 });
            list.Add(new { name = "TPE", fullName = "Taoyuan International Airport", longitude = 121.2333, latitude = 25.0778 });
            list.Add(new { name = "DYU", fullName = "Dushanbe International Airport", longitude = 68.8025, latitude = 38.5133 });
            list.Add(new { name = "BKK", fullName = "Suvarnabhumi Airport", longitude = 100.7500, latitude = 13.6811 });
            list.Add(new { name = "DIL", fullName = "Presidente Nicolau Lobato International Airport", longitude = 125.5736, latitude = -8.5564 });
            list.Add(new { name = "IST", fullName = "Istanbul Airport", longitude = 28.7519, latitude = 41.2750 });
            list.Add(new { name = "ASB", fullName = "Ashgabat International Airport", longitude = 58.3636, latitude = 37.9786 });
            list.Add(new { name = "DXB", fullName = "Dubai International Airport", longitude = 55.3644, latitude = 25.2532 });
            list.Add(new { name = "TAS", fullName = "Tashkent International Airport", longitude = 69.2692, latitude = 41.2642 });
            list.Add(new { name = "SGN", fullName = "Tan Son Nhat International Airport", longitude = 106.6811, latitude = 10.8236 });
            list.Add(new { name = "SAH", fullName = "Sana'a International Airport", longitude = 44.2075, latitude = 15.4794 });
            list.Add(new { name = "TIA", fullName = "Tirana International Airport Nënë Tereza", longitude = 19.7206, latitude = 41.4142 });
            list.Add(new { name = "LEU", fullName = "Andorra–La Seu d'Urgell Airport", longitude = 1.4472, latitude = 42.3658 });
            list.Add(new { name = "VIE", fullName = "Vienna International Airport", longitude = 16.5644, latitude = 48.1406 });
            list.Add(new { name = "MSQ", fullName = "Minsk National Airport", longitude = 28.0292, latitude = 53.88 });
            list.Add(new { name = "BRU", fullName = "Brussels Airport", longitude = 4.4537, latitude = 50.9014 });
            list.Add(new { name = "SJJ", fullName = "Sarajevo International Airport", longitude = 18.3314, latitude = 43.8242 });
            list.Add(new { name = "SOF", fullName = "Sofia Airport", longitude = 23.4064, latitude = 42.6969 });
            list.Add(new { name = "ZAG", fullName = "Zagreb Franjo Tuđman Airport", longitude = 16.0644, latitude = 45.7425 });
            list.Add(new { name = "PRG", fullName = "Václav Havel Airport Prague", longitude = 14.26, latitude = 50.1006 });
            list.Add(new { name = "CPH", fullName = "Copenhagen Airport", longitude = 12.6500, latitude = 55.6170 });
            list.Add(new { name = "TLL", fullName = "Tallinn Airport", longitude = 24.8325, latitude = 59.4133 });
            list.Add(new { name = "HEL", fullName = "Helsinki Airport", longitude = 24.9633, latitude = 60.3172 });
            list.Add(new { name = "CDG", fullName = "Charles de Gaulle Airport", longitude = 2.5497, latitude = 49.0097 });
            list.Add(new { name = "FRA", fullName = "Frankfurt Airport", longitude = 8.5706, latitude = 50.0379 });
            list.Add(new { name = "ATH", fullName = "Athens International Airport", longitude = 23.9497, latitude = 37.9364 });
            list.Add(new { name = "BUD", fullName = "Budapest Ferenc Liszt International Airport", longitude = 19.2611, latitude = 47.4369 });
            list.Add(new { name = "KEF", fullName = "Keflavík International Airport", longitude = -22.6056, latitude = 63.9856 });
            list.Add(new { name = "DUB", fullName = "Dublin Airport", longitude = -6.2519, latitude = 53.4219 });
            list.Add(new { name = "FCO", fullName = "Leonardo da Vinci International Airport", longitude = 12.2500, latitude = 41.8003 });
            list.Add(new { name = "PRN", fullName = "Adem Jashari International Airport", longitude = 20.9100, latitude = 42.5722 });
            list.Add(new { name = "RIX", fullName = "Riga International Airport", longitude = 23.9733, latitude = 56.9231 });
            list.Add(new { name = "LIE", fullName = "Liechtenstein Airport", longitude = 9.5214, latitude = 47.1414 });
            list.Add(new { name = "VNO", fullName = "Vilnius Airport", longitude = 25.2861, latitude = 54.6342 });
            list.Add(new { name = "LUX", fullName = "Luxembourg Airport", longitude = 6.2111, latitude = 49.6269 });
            list.Add(new { name = "MLA", fullName = "Malta International Airport", longitude = 14.4778, latitude = 35.8575 });
            list.Add(new { name = "KIV", fullName = "Chișinău International Airport", longitude = 28.0278, latitude = 46.9278 });
            list.Add(new { name = "NCE", fullName = "Nice Côte d'Azur Airport", longitude = 7.2167, latitude = 43.6597 });
            list.Add(new { name = "TGD", fullName = "Podgorica Airport", longitude = 19.2614, latitude = 42.3597 });
            list.Add(new { name = "AMS", fullName = "Amsterdam Airport Schiphol", longitude = 4.7639, latitude = 52.3086 });
            list.Add(new { name = "SKP", fullName = "Skopje International Airport", longitude = 21.6219, latitude = 41.9611 });
            list.Add(new { name = "OSL", fullName = "Oslo Gardermoen Airport", longitude = 11.1000, latitude = 60.1939 });
            list.Add(new { name = "WAW", fullName = "Warsaw Chopin Airport", longitude = 20.9772, latitude = 52.1650 });
            list.Add(new { name = "LIS", fullName = "Lisbon Humberto Delgado Airport", longitude = -9.1342, latitude = 38.7742 });
            list.Add(new { name = "OTP", fullName = "Henri Coandă International Airport", longitude = 26.1025, latitude = 44.5714 });
            list.Add(new { name = "SVO", fullName = "Sheremetyevo International Airport", longitude = 37.4142, latitude = 55.9722 });
            list.Add(new { name = "RSM", fullName = "San Marino Airport", longitude = 12.4606, latitude = 43.9333 });
            list.Add(new { name = "BEG", fullName = "Belgrade Nikola Tesla Airport", longitude = 20.3025, latitude = 44.8186 });
            list.Add(new { name = "KSC", fullName = "Košice International Airport", longitude = 21.2414, latitude = 48.6639 });
            list.Add(new { name = "LJU", fullName = "Ljubljana Jože Pučnik Airport", longitude = 14.4572, latitude = 46.2250 });
            list.Add(new { name = "MAD", fullName = "Adolfo Suárez Madrid–Barajas Airport", longitude = -3.5667, latitude = 40.4719 });
            list.Add(new { name = "ARN", fullName = "Stockholm Arlanda Airport", longitude = 17.9297, latitude = 59.6519 });
            list.Add(new { name = "ZRH", fullName = "Zurich Airport", longitude = 8.5592, latitude = 47.4647 });
            list.Add(new { name = "KBP", fullName = "Boryspil International Airport", longitude = 30.8944, latitude = 50.3456 });
            list.Add(new { name = "LHR", fullName = "London Heathrow Airport", longitude = -0.4543, latitude = 51.4700 });
            list.Add(new { name = "FCO", fullName = "Leonardo da Vinci International Airport", longitude = 12.2500, latitude = 41.8003 });
            list.Add(new { name = "AHO", fullName = "Fertilia Airport", longitude = 8.2928, latitude = 40.5778 });
            list.Add(new { name = "JER", fullName = "Jersey Airport", longitude = -2.2133, latitude = 49.2133 });
            list.Add(new { name = "FAE", fullName = "Vágar Airport", longitude = -7.2778, latitude = 62.0906 });
            list.Add(new { name = "GCI", fullName = "Guernsey Airport", longitude = -2.6019, latitude = 49.4147 });
            list.Add(new { name = "IOM", fullName = "Isle of Man Airport", longitude = -4.6231, latitude = 54.0833 });
            list.Add(new { name = "AXA", fullName = "Clayton J. Lloyd International Airport", longitude = -63.0606, latitude = 18.2206 });
            list.Add(new { name = "ANU", fullName = "V. C. Bird International Airport", longitude = -61.7922, latitude = 17.1892 });
            list.Add(new { name = "NAS", fullName = "Lynden Pindling International Airport", longitude = -77.4653, latitude = 25.0383 });
            list.Add(new { name = "BGI", fullName = "Grantley Adams International Airport", longitude = -59.4928, latitude = 13.0742 });
            list.Add(new { name = "BZE", fullName = "Philip S. W. Goldson International Airport", longitude = -88.3086, latitude = 17.5397 });
            list.Add(new { name = "BDA", fullName = "L.F. Wade International Airport", longitude = -64.6789, latitude = 32.3647 });
            list.Add(new { name = "EIS", fullName = "Terrance B. Lettsome International Airport", longitude = -64.5561, latitude = 18.4478 });
            list.Add(new { name = "YYZ", fullName = "Toronto Pearson International Airport", longitude = -79.6276, latitude = 43.6777 });
            list.Add(new { name = "GCM", fullName = "Owen Roberts International Airport", longitude = -81.2542, latitude = 19.3133 });
            list.Add(new { name = "SJO", fullName = "Juan Santamaría International Airport", longitude = -84.2083, latitude = 9.9986 });
            list.Add(new { name = "HAV", fullName = "José Martí International Airport", longitude = -82.4097, latitude = 22.9897 });
            list.Add(new { name = "CUR", fullName = "Hato International Airport", longitude = -68.9597, latitude = 12.5014 });
            list.Add(new { name = "DOM", fullName = "Douglas-Charles Airport", longitude = -61.2928, latitude = 15.5478 });
            list.Add(new { name = "SDQ", fullName = "Las Américas International Airport", longitude = -69.7364, latitude = 18.4297 });
            list.Add(new { name = "SAL", fullName = "Monseñor Óscar Arnulfo Romero International Airport", longitude = -89.0556, latitude = 13.4408 });
            list.Add(new { name = "GOH", fullName = "Nuuk Airport", longitude = -51.7214, latitude = 64.1908 });
            list.Add(new { name = "GND", fullName = "Maurice Bishop International Airport", longitude = -61.7833, latitude = 12.0056 });
            list.Add(new { name = "GUA", fullName = "La Aurora International Airport", longitude = -90.5278, latitude = 14.5833 });
            list.Add(new { name = "PAP", fullName = "Toussaint Louverture International Airport", longitude = -72.2892, latitude = 18.5797 });
            list.Add(new { name = "TGU", fullName = "Toncontín International Airport", longitude = -87.2178, latitude = 13.4442 });
            list.Add(new { name = "KIN", fullName = "Norman Manley International Airport", longitude = -76.7878, latitude = 17.9356 });
            list.Add(new { name = "CUN", fullName = "Cancún International Airport", longitude = -86.8772, latitude = 21.0361 });
            list.Add(new { name = "MNI", fullName = "John A. Osborne Airport", longitude = -62.1878, latitude = 16.7422 });
            list.Add(new { name = "MGA", fullName = "Augusto C. Sandino International Airport", longitude = -86.1714, latitude = 12.1417 });
            list.Add(new { name = "PTY", fullName = "Tocumen International Airport", longitude = -79.3833, latitude = 9.0714 });
            list.Add(new { name = "SJU", fullName = "Luis Muñoz Marín International Airport", longitude = -66.0014, latitude = 18.4397 });
            list.Add(new { name = "SKB", fullName = "Robert Llewellyn Bradshaw International Airport", longitude = -62.9986, latitude = 17.3022 });
            list.Add(new { name = "UVF", fullName = "Hewanorra International Airport", longitude = -61.175, latitude = 13.7333 });
            list.Add(new { name = "FSP", fullName = "St. Pierre Airport", longitude = -56.1778, latitude = 46.7708 });
            list.Add(new { name = "SVD", fullName = "Argyle International Airport", longitude = -61.1378, latitude = 13.2639 });
            list.Add(new { name = "SBH", fullName = "Gustaf III Airport", longitude = -62.8497, latitude = 17.9028 });
            list.Add(new { name = "SFG", fullName = "Grand Case Espérance Airport", longitude = -63.0508, latitude = 18.1064 });
            list.Add(new { name = "PLS", fullName = "Providenciales International Airport", longitude = -72.2658, latitude = 21.7733 });
            list.Add(new { name = "ATL", fullName = "Hartsfield-Jackson Atlanta International Airport", longitude = -84.4279, latitude = 33.6407 });
            list.Add(new { name = "STT", fullName = "Cyril E. King Airport", longitude = -64.9731, latitude = 18.3372 });
            list.Add(new { name = "AUA", fullName = "Queen Beatrix International Airport", longitude = -70.015, latitude = 12.501 });
            list.Add(new { name = "EZE", fullName = "Ministro Pistarini International Airport", longitude = -58.4436, latitude = -34.8222 });
            list.Add(new { name = "VVI", fullName = "Viru Viru International Airport", longitude = -63.1292, latitude = -17.6444 });
            list.Add(new { name = "GRU", fullName = "São Paulo/Guarulhos International Airport", longitude = -46.5386, latitude = -23.4356 });
            list.Add(new { name = "SCL", fullName = "Arturo Merino Benítez International Airport", longitude = -70.7858, latitude = -33.3933 });
            list.Add(new { name = "BOG", fullName = "El Dorado International Airport", longitude = -74.1469, latitude = 4.7019 });
            list.Add(new { name = "UIO", fullName = "Mariscal Sucre International Airport", longitude = -78.3572, latitude = -0.1328 });
            list.Add(new { name = "MPN", fullName = "RAF Mount Pleasant", longitude = -58.4472, latitude = -51.8228 });
            list.Add(new { name = "GEO", fullName = "Cheddi Jagan International Airport", longitude = -58.2544, latitude = 6.4936 });
            list.Add(new { name = "ASU", fullName = "Silvio Pettirossi International Airport", longitude = -57.5211, latitude = -25.2292 });
            list.Add(new { name = "LIM", fullName = "Jorge Chávez International Airport", longitude = -77.1101, latitude = -12.0219 });
            list.Add(new { name = "PBM", fullName = "Zanderij International Airport", longitude = -55.1875, latitude = 5.4528 });
            list.Add(new { name = "POS", fullName = "Piarco International Airport", longitude = -61.3375, latitude = 10.5958 });
            list.Add(new { name = "MVD", fullName = "Carrasco International Airport", longitude = -56.0272, latitude = -34.8347 });
            list.Add(new { name = "CCS", fullName = "Simón Bolívar International Airport", longitude = -67.1806, latitude = 10.6014 });
            list.Add(new { name = "PPG", fullName = "Pago Pago International Airport", longitude = -170.721, latitude = -14.333 });
            list.Add(new { name = "SYD", fullName = "Sydney Kingsford Smith Airport", longitude = 151.177, latitude = -33.939 });
            list.Add(new { name = "RAR", fullName = "Rarotonga International Airport", longitude = -159.774, latitude = -21.207 });
            list.Add(new { name = "PNI", fullName = "Pohnpei International Airport", longitude = 158.215, latitude = 6.972 });
            list.Add(new { name = "NAN", fullName = "Nadi International Airport", longitude = 177.443, latitude = -17.755 });
            list.Add(new { name = "PPT", fullName = "Faa'a International Airport", longitude = -149.607, latitude = -17.553 });
            list.Add(new { name = "GUM", fullName = "Antonio B. Won Pat International Airport", longitude = 144.896, latitude = 13.493 });
            list.Add(new { name = "TRW", fullName = "Tucson International Airport", longitude = -110.941, latitude = 32.131 });
            list.Add(new { name = "MAJ", fullName = "Marshall Islands International Airport", longitude = 171.280, latitude = 7.107 });
            list.Add(new { name = "INU", fullName = "Nauru International Airport", longitude = 166.919, latitude = -0.547 });
            list.Add(new { name = "NOU", fullName = "La Tontouta International Airport", longitude = 166.213, latitude = -22.013 });
            list.Add(new { name = "AKL", fullName = "Auckland Airport", longitude = 174.783, latitude = -37.008 });
            list.Add(new { name = "IUE", fullName = "Niue International Airport", longitude = -169.918, latitude = -19.070 });
            list.Add(new { name = "NLK", fullName = "Norfolk Island Airport", longitude = 167.944, latitude = -29.040 });
            list.Add(new { name = "SPN", fullName = "Francisco C. Ada/Saipan International Airport", longitude = 145.729, latitude = 15.182 });
            list.Add(new { name = "ROR", fullName = "Roman Tmetuchl International Airport", longitude = 134.548, latitude = 7.348 });
            list.Add(new { name = "PNH", fullName = "Phnom Penh International Airport", longitude = 104.844, latitude = 11.546 });
            list.Add(new { name = "PIC", fullName = "Pitcairn Island Airport", longitude = -130.083, latitude = -24.703 });
            list.Add(new { name = "APW", fullName = "Faleolo International Airport", longitude = -172.007, latitude = -13.829 });
            list.Add(new { name = "HIR", fullName = "Henderson International Airport", longitude = 160.045, latitude = -9.433 });
            list.Add(new { name = "TBU", fullName = "Fuaʻamotu International Airport", longitude = -175.150, latitude = -21.241 });
            list.Add(new { name = "FUN", fullName = "Funafuti International Airport", longitude = 179.194, latitude = -7.473 });
            list.Add(new { name = "VLI", fullName = "Bauerfield International Airport", longitude = 168.309, latitude = -17.701 });
            list.Add(new { name = "WLS", fullName = "Hihifo Airport", longitude = -178.120, latitude = -13.279 });
            list.Add(new { name = "NZIR", fullName = "McMurdo Station Ice Runway", longitude = 166.6667, latitude = -77.846 });
            list.Add(new { name = "AT1", fullName = "Base Dumont d'Urville Ice Runway", longitude = 140.0017, latitude = -66.6608 });
            list.Add(new { name = "HIM", fullName = "Heard Island Research Airstrip", longitude = 73.5, latitude = -53.1 });
            list.Add(new { name = "SGS", fullName = "King Edward Point Heliport", longitude = -36.5000, latitude = -54.2833 });
            list.Add(new { name = "LAX", fullName = "Los Angeles International Airport", longitude = -118.4081, latitude = 33.9416 });
            list.Add(new { name = "ORD", fullName = "O'Hare International Airport", longitude = -87.9048, latitude = 41.9742 });
            list.Add(new { name = "DFW", fullName = "Dallas/Fort Worth International Airport", longitude = -97.0403, latitude = 32.8998 });
            list.Add(new { name = "DEN", fullName = "Denver International Airport", longitude = -104.6737, latitude = 39.8561 }); 
            list.Add(new { name = "MIA", fullName = "Miami International Airport", longitude = -80.2906, latitude = 25.7959 }); 

            
            return Ok(list);
        }
    }
}
